# Generated by Django 4.2.6 on 2023-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Роман', 'Роман'), ('Детектив', 'Детектив'), ('Фэнтези', 'Фэнтези'), ('Научная фантастика', 'Научная фантастика'), ('Документальная литература', 'Документальная литература')], default=('Роман', 'Роман'), max_length=100, null=True),
        ),
    ]
