# Generated by Django 4.2.6 on 2023-11-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_reviewbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
